"use client";
import { useMemo, useState } from "react";

const initialSubjects = ["Mathematics", "English", "Kiswahili", "Chemistry", "Physics", "Biology", "CRE", "Drawing & Design"];
const defaultScores = [62, 70, 67, 76, 81, 78];
const days = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];

export default function Home() {
  const [tab, setTab] = useState("dashboard");
  const [subjects, setSubjects] = useState(initialSubjects);
  const [newSubject, setNewSubject] = useState("");
  const [activeSubject, setActiveSubject] = useState("Mathematics");
  const [diary, setDiary] = useState("");
  const [entries, setEntries] = useState<string[]>([]);
  const [score, setScore] = useState("");
  const [scoreSubject, setScoreSubject] = useState("Mathematics");
  const [scores, setScores] = useState<{subject:string; score:number}[]>([]);

  const allScores = [...defaultScores, ...scores.map(x => x.score)];
  const average = useMemo(() => Math.round(allScores.reduce((a,b)=>a+b,0)/allScores.length), [scores]);
  const addSubject = () => { const s = newSubject.trim(); if(s && !subjects.includes(s)){setSubjects([...subjects,s]);setNewSubject("");} };
  const addScore = () => { const n = Number(score); if(n>=0 && n<=100){setScores([...scores,{subject:scoreSubject,score:n}]);setScore("");} };
  const saveDiary = () => { if(diary.trim()){setEntries([diary.trim(),...entries]);setDiary("");} };

  return <main className="min-h-screen bg-[#f7f9fc] text-slate-800">
    <header className="sticky top-0 z-30 border-b border-slate-200 bg-white/95 backdrop-blur"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4 sm:px-6 lg:px-8"><a href="/" className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-blue-600 font-bold text-white">S</span><span className="font-bold">StudyMate <span className="font-normal text-blue-600">AI</span></span></a><nav className="hidden gap-1 text-sm md:flex">{[["dashboard","Dashboard"],["planner","Planner"],["habits","Study habits"],["scores","Exam scores"],["diary","Study diary"],["profile","Profile"]].map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`rounded-lg px-3 py-2 ${tab===id?"bg-blue-50 font-medium text-blue-700":"text-slate-500 hover:bg-slate-50"}`}>{label}</button>)}</nav><button onClick={()=>setTab("profile")} className="grid h-9 w-9 place-items-center rounded-full border border-slate-200 bg-slate-50 text-sm font-semibold text-slate-600">V</button></div></header>
    <div className="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
      {tab === "dashboard" && <><section className="grid gap-6 lg:grid-cols-[1fr_320px]"><div><div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-sm font-semibold text-slate-900">Your education workspace</p><h1 className="mt-2 text-3xl font-bold tracking-tight text-slate-900">Plan. Study. Track. Improve.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">StudyMate combines your AI assistant, personal timetable, study diary, habits and academic performance in one place.</p><div className="mt-6 grid gap-3 sm:grid-cols-3"><button onClick={()=>setTab("planner")} className="rounded-xl bg-blue-600 p-4 text-left text-white"><b className="block text-sm">Build timetable</b><span className="mt-1 block text-xs text-blue-100">Plan your week</span></button><button onClick={()=>setTab("habits")} className="rounded-xl border border-slate-200 p-4 text-left"><b className="block text-sm">Track habits</b><span className="mt-1 block text-xs text-slate-400">See your study pattern</span></button><button onClick={()=>setTab("scores")} className="rounded-xl border border-slate-200 p-4 text-left"><b className="block text-sm">Record scores</b><span className="mt-1 block text-xs text-slate-400">Watch your grades grow</span></button></div></div><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric title="Study today" value="42 min" sub="Goal 60 min"/><Metric title="Weekly time" value="4h 32m" sub="+18% this week"/><Metric title="Exam average" value={`${average}%`} sub="Recorded results"/><Metric title="Streak" value="7 days 🔥" sub="Keep going"/></div></div><aside className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-semibold">Today&apos;s plan</h2>{[["08:00","Mathematics"],["10:00","Physics"],["14:00","Chemistry"],["17:00","Biology"]].map(([t,s])=><div key={t} className="mt-3 flex items-center gap-3 rounded-xl bg-slate-50 p-3"><span className="w-12 text-xs font-semibold text-blue-600">{t}</span><span className="text-sm">{s}</span></div>)}<button onClick={()=>setTab("planner")} className="mt-4 w-full rounded-lg border border-slate-200 py-2 text-xs font-medium">Edit timetable</button></aside></section><section className="mt-6 rounded-2xl border border-slate-200 bg-white p-6"><div className="flex items-center justify-between"><div><h2 className="font-bold text-slate-900">My subjects</h2><p className="mt-1 text-xs text-slate-400">Select what you are currently focusing on.</p></div><button onClick={()=>setTab("profile")} className="text-xs font-medium text-blue-600">Manage subjects →</button></div><div className="mt-4 flex flex-wrap gap-2">{subjects.map(s=><button key={s} onClick={()=>setActiveSubject(s)} className={`rounded-lg px-3 py-2 text-xs ${activeSubject===s?"bg-blue-600 text-white":"bg-slate-50 text-slate-600"}`}>{s}</button>)}</div></section></>}

      {tab === "planner" && <Page title="My study planner" desc="Create a timetable that fits your school day, free time and exam goals."><div className="grid gap-6 lg:grid-cols-[1fr_300px]"><div className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-semibold">Weekly timetable</h2>{days.map((day,i)=><div key={day} className="mt-3 grid grid-cols-[55px_1fr] gap-3 rounded-xl border border-slate-100 p-3"><span className="pt-2 text-xs font-semibold text-slate-500">{day}</span><div className="flex flex-wrap gap-2">{subjects.slice(i%3,i%3+2).map(s=><span key={s} className="rounded-lg bg-blue-50 px-3 py-2 text-xs text-blue-700">{s} · {i<5?"1 hr":"2 hrs"}</span>)}</div></div>)}</div><div className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-semibold">Planner settings</h2><label className="mt-4 block text-xs text-slate-500">Daily study target</label><select className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm"><option>1 hour</option><option>2 hours</option><option>3 hours</option><option>4+ hours</option></select><label className="mt-4 block text-xs text-slate-500">Exam date</label><input type="date" className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm"/><button className="mt-5 w-full rounded-lg bg-blue-600 py-2.5 text-xs font-semibold text-white">Generate timetable</button></div></div></Page>}

      {tab === "habits" && <Page title="Study habits" desc="Understand when you study, how consistently you study and where your time goes."><div className="grid gap-6 lg:grid-cols-[1fr_300px]"><div className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="font-semibold">Study time this week</h2><div className="mt-8 flex h-64 items-end gap-3">{[42,65,48,78,56,88,68].map((v,i)=><div key={i} className="flex flex-1 flex-col items-center gap-2"><span className="text-[10px] text-slate-400">{v}m</span><div className="w-full rounded-t-lg bg-blue-500" style={{height:`${v}%`}}/><span className="text-[10px] text-slate-400">{days[i]}</span></div>)}</div></div><div className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="font-semibold">Study habit split</h2><div className="mx-auto mt-6 h-40 w-40 rounded-full" style={{background:"conic-gradient(#2563eb 0 45%, #60a5fa 45% 72%, #bfdbfe 72% 88%, #e2e8f0 88% 100%)"}}/><div className="mt-5 space-y-2 text-xs">{[["Focused study","45%"],["Revision","27%"],["Practice","16%"],["Other","12%"]].map(([a,b])=><div key={a} className="flex justify-between"><span className="text-slate-500">{a}</span><b>{b}</b></div>)}</div></div></div></Page>}

      {tab === "scores" && <Page title="Exam score tracker" desc="Enter your marks after every test or exam and watch your academic performance change automatically."><div className="grid gap-6 lg:grid-cols-[1fr_300px]"><div className="rounded-2xl border border-slate-200 bg-white p-6"><div className="flex items-center justify-between"><h2 className="font-semibold">Performance trend</h2><span className="rounded-full bg-blue-50 px-3 py-1 text-xs text-blue-700">Average {average}%</span></div><div className="mt-8 flex h-64 items-end gap-2 border-b border-slate-100">{allScores.map((v,i)=><div key={i} className="group relative flex h-full flex-1 items-end"><div className="w-full rounded-t-md bg-blue-500" style={{height:`${v}%`}}/><span className="absolute -top-5 left-1/2 -translate-x-1/2 text-[10px] text-slate-400 opacity-0 group-hover:opacity-100">{v}%</span></div>)}</div><div className="mt-3 flex justify-between text-[10px] text-slate-400"><span>First result</span><span>Latest result</span></div></div><div className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-semibold">Add result</h2><select value={scoreSubject} onChange={e=>setScoreSubject(e.target.value)} className="mt-4 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm">{subjects.map(s=><option key={s}>{s}</option>)}</select><input value={score} onChange={e=>setScore(e.target.value)} type="number" min="0" max="100" placeholder="Score out of 100" className="mt-2 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm"/><button onClick={addScore} className="mt-2 w-full rounded-lg bg-blue-600 py-2.5 text-xs font-semibold text-white">Add score</button><div className="mt-5 border-t pt-4 text-xs text-slate-500">Results recorded: <b className="text-slate-800">{scores.length}</b></div></div></div></Page>}

      {tab === "diary" && <Page title="Study diary" desc="Keep a private record of your learning journey, reflections, challenges and wins."><div className="grid gap-6 lg:grid-cols-[1fr_300px]"><div className="rounded-2xl border border-slate-200 bg-white p-5"><textarea value={diary} onChange={e=>setDiary(e.target.value)} rows={8} placeholder="Write about today&apos;s study session... What did you learn? What was difficult? What will you improve tomorrow?" className="w-full resize-none rounded-xl border border-slate-200 p-4 text-sm outline-none focus:border-blue-400"/><button onClick={saveDiary} className="mt-3 rounded-lg bg-blue-600 px-4 py-2.5 text-xs font-semibold text-white">Save diary entry</button><div className="mt-6 space-y-3">{entries.map((e,i)=><article key={i} className="rounded-xl bg-slate-50 p-4"><p className="text-[10px] uppercase tracking-wider text-slate-400">Study reflection</p><p className="mt-2 text-sm leading-6 text-slate-600">{e}</p></article>)}</div></div><div className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-semibold">Reflection prompts</h2>{["What did I learn today?","What topic needs more revision?","What study method worked?","What is tomorrow&apos;s target?"].map(x=><div key={x} className="mt-3 rounded-lg bg-slate-50 p-3 text-xs text-slate-600">{x}</div>)}</div></div></Page>}

      {tab === "profile" && <Page title="My student profile" desc="Personalize StudyMate around your education, subjects and goals."><div className="grid gap-6 md:grid-cols-2"><div className="rounded-2xl border border-slate-200 bg-white p-6"><div className="flex items-center gap-4"><div className="grid h-16 w-16 place-items-center rounded-full bg-blue-100 text-xl font-bold text-blue-700">V</div><div><h2 className="font-bold">My Profile</h2><p className="text-xs text-slate-400">Student learning account</p></div></div><input placeholder="Your name" className="mt-6 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm"/><input placeholder="School / institution" className="mt-2 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm"/><select className="mt-2 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm"><option>Form 3</option><option>Form 1</option><option>Form 2</option><option>Form 4</option></select></div><div className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="font-semibold">My subjects</h2><div className="mt-4 flex flex-wrap gap-2">{subjects.map(s=><button key={s} onClick={()=>setActiveSubject(s)} className={`rounded-lg px-3 py-2 text-xs ${activeSubject===s?"bg-blue-600 text-white":"bg-blue-50 text-blue-700"}`}>{s}</button>)}</div><div className="mt-5 flex gap-2"><input value={newSubject} onChange={e=>setNewSubject(e.target.value)} placeholder="Add another subject" className="min-w-0 flex-1 rounded-lg border border-slate-200 px-3 py-2 text-sm"/><button onClick={addSubject} className="rounded-lg bg-blue-600 px-3 py-2 text-xs font-semibold text-white">Add</button></div></div></div></Page>}
    </div>
  </main>;
}

function Metric({title,value,sub}:{title:string,value:string,sub:string}){return <div className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs text-slate-400">{title}</p><p className="mt-1 text-2xl font-bold text-slate-900">{value}</p><p className="mt-1 text-xs text-slate-400">{sub}</p></div>}
function Page({title,desc,children}:{title:string,desc:string,children:React.ReactNode}){return <section><div className="mb-6"><h1 className="text-3xl font-bold tracking-tight text-slate-900">{title}</h1><p className="mt-2 text-sm text-slate-500">{desc}</p></div>{children}</section>}
